"""rename department

Revision ID: 078c3e690793
Revises: 76c6e6776493
Create Date: 2024-06-26 07:11:07.546720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078c3e690793'
down_revision = '76c6e6776493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
